/**
 * Build src/data/kanji.ts from the source readings + generated meanings.
 *
 *   node scripts/build-data.mjs
 *
 * Inputs (in scripts/):
 *   readings.json  — [{ id, kanji, readings[] }]  (parsed from the source TSV)
 *   meanings.json  — [{ id, kanji, meaning, meanings[] }]  (optional; verified glosses)
 *
 * If meanings.json is missing, a placeholder meaning is used so the app still
 * compiles. Re-run after meanings.json is available to bake in real glosses.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const readings = JSON.parse(readFileSync(join(here, 'readings.json'), 'utf8'))

let meanings = []
const meaningsPath = join(here, 'meanings.json')
if (existsSync(meaningsPath)) {
  meanings = JSON.parse(readFileSync(meaningsPath, 'utf8'))
} else {
  console.warn('⚠  scripts/meanings.json not found — using placeholder meanings.')
}

const meaningById = new Map(meanings.map((m) => [m.id, m]))

const LEVEL = 'N3'

const entries = readings.map((r) => {
  const m = meaningById.get(r.id)
  const meaning = m?.meaning ?? '(meaning pending)'
  const accepted = Array.isArray(m?.meanings) && m.meanings.length ? m.meanings : [meaning.toLowerCase()]
  return {
    id: r.id,
    kanji: r.kanji,
    readings: r.readings,
    meaning,
    meanings: accepted,
    level: LEVEL,
  }
})

const banner = `/* AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
   To add or change kanji, edit scripts/readings.json + scripts/meanings.json
   and re-run \`npm run data:build\`, or edit this file's data directly. */`

const body = entries
  .map(
    (e) =>
      `  { id: ${e.id}, kanji: ${JSON.stringify(e.kanji)}, readings: ${JSON.stringify(
        e.readings,
      )}, meaning: ${JSON.stringify(e.meaning)}, meanings: ${JSON.stringify(e.meanings)}, level: '${e.level}' },`,
  )
  .join('\n')

const out = `${banner}
import type { Kanji } from './types'

export const KANJI: Kanji[] = [
${body}
]
`

const target = join(root, 'src', 'data', 'kanji.ts')
writeFileSync(target, out)
console.log(`✓ Wrote ${entries.length} kanji → src/data/kanji.ts (${meanings.length ? 'with' : 'WITHOUT'} meanings)`)

/* ----------------------------- vocabulary deck ---------------------------- */
const vocabPath = join(here, 'vocab.json')
if (existsSync(vocabPath)) {
  const vocab = JSON.parse(readFileSync(vocabPath, 'utf8'))

  const tokens = (meaning) =>
    meaning
      .split(/[/,;]|・/)
      .map((s) => s.trim())
      .filter(Boolean)

  // Merge duplicate word strings (the source lists some words in two chapters,
  // and a few are homographs with different readings) into one card carrying
  // the union of readings and meaning senses — like the kanji cards.
  const merged = new Map()
  for (const v of vocab) {
    const existing = merged.get(v.word)
    if (existing) {
      if (!existing.readings.includes(v.reading)) existing.readings.push(v.reading)
      for (const t of tokens(v.meaning)) {
        if (!existing.senses.some((s) => s.toLowerCase() === t.toLowerCase())) existing.senses.push(t)
      }
    } else {
      merged.set(v.word, { id: v.id, word: v.word, readings: [v.reading], senses: tokens(v.meaning) })
    }
  }

  const vEntries = [...merged.values()]
    .sort((a, b) => a.id - b.id)
    .map((v, i) => ({
      id: i + 1,
      kanji: v.word,
      readings: v.readings,
      meaning: v.senses.join(' / '),
      meanings: Array.from(new Set(v.senses.map((s) => s.toLowerCase()))),
      level: LEVEL,
    }))

  const vBody = vEntries
    .map(
      (e) =>
        `  { id: ${e.id}, kanji: ${JSON.stringify(e.kanji)}, readings: ${JSON.stringify(
          e.readings,
        )}, meaning: ${JSON.stringify(e.meaning)}, meanings: ${JSON.stringify(e.meanings)}, level: '${
          e.level
        }' },`,
    )
    .join('\n')

  const vOut = `${banner.replace('kanji', 'vocabulary')}
import type { Kanji } from './types'

export const VOCAB: Kanji[] = [
${vBody}
]
`
  writeFileSync(join(root, 'src', 'data', 'vocab.ts'), vOut)
  console.log(`✓ Wrote ${vEntries.length} vocab words → src/data/vocab.ts`)
} else {
  console.warn('⚠  scripts/vocab.json not found — skipping vocab deck.')
}
